### ISSUE TITLE
Missing Ground in Falkreath 

### ISSUE THREAD

**Issue by sanketshah1086** [Zeagl3/Skybax#1]
See attached pictures - let me know if it's just me or it's actually an issue.. I haven't added anything to the list

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 01 20 - 14 17 15 37](https://user-images.githubusercontent.com/65946193/150415749-b4989a2a-54fe-4e93-96eb-f8367a533c65.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 01 20 - 14 15 27 29](https://user-images.githubusercontent.com/65946193/150415752-dc06f14e-e293-4bc3-b2a9-c662cbedeb38.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 01 20 - 14 16 00 14](https://user-images.githubusercontent.com/65946193/150415755-6fff32b5-7ceb-4ecd-8419-1e2c0ebfa02f.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 01 20 - 14 16 52 62](https://user-images.githubusercontent.com/65946193/150415767-3a5b2580-aee1-489f-8487-65fdf5e42502.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 01 20 - 14 16 11 33](https://user-images.githubusercontent.com/65946193/150415762-e2aa3f80-eccc-4c36-b298-354d4fcc0608.png)

**Comment by Zeagl3** [comment]
Changed the Falkreath overhaul, no more missing ground.
