### ISSUE TITLE
Auri's ride

### ISSUE THREAD

**Issue by FiraNGit** [Zeagl3/Skybax#11]
She spawn 2 mounts when I ride, Thistlefoot and regular one
![image](https://user-images.githubusercontent.com/98646215/151710028-e5376c74-f183-44c2-8736-5ded947ecc23.png)
Using only (wrong) one obviously
![image](https://user-images.githubusercontent.com/98646215/151710004-6bdef79d-4c14-46ac-a2c2-3488c900de8c.png)
Edit: after a while she ride another one, something weird is going on
![image](https://user-images.githubusercontent.com/98646215/151710284-c778911c-eb39-4d38-ac12-7b4af507b718.png)

**Comment by Zeagl3** [comment]
DId you import her into NFF?

**Comment by Zeagl3** [comment]
In NFF Settings, disable 'Allow Horse' for her, then she will not spawn 2 mounts.
![image](https://i.imgur.com/aZyP50F.png)
