### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by RayKovalsky** [Zeagl3/Skybax#16]
There seems to be a problem with the installation process, right at the end of it (screenshot), any help? Thanks!

![Skybax Error](https://user-images.githubusercontent.com/116916410/198717993-269b4b93-4896-495c-8d73-bbf0f0fc637c.png)

**Comment by Zeagl3** [comment]
Will be fixed in v1.5

**Comment by RayKovalsky** [comment]
Ooh that's a pity, i was hoping it could be a minor issue. If the 1.4 version is not working anymore, you know...It might help if you put it under maintenance on wabbajack. Anyway, thanks a lot for your hard work building this list, it looks amazing! Hope to see that 1.5v soon! ;)
