### ISSUE TITLE
Weird Hair Texture

### ISSUE THREAD

**Issue by Hansamuna** [Zeagl3/Skybax#2]
Caused by : Pandorable's NPCs - Males 2 | Conflicting with | Pride of Skyrim
Brand-Shei in Riften at his stall
![2022-01-20 18_32_20-Greenshot](https://user-images.githubusercontent.com/86857975/150439306-7324de7c-d6e4-427d-a47c-84257998ad2b.png)
Vekel the Man in The Ragged Flagon
![2022-01-21 13_38_49-Greenshot](https://user-images.githubusercontent.com/86857975/150582304-69d44811-c86b-4108-a66f-14e6fc16b7b9.png)
Saerlund outside Mistveil Keep in Riften
![2022-01-22 19_23_59-Greenshot](https://user-images.githubusercontent.com/86857975/150659852-3aadfb7a-1a76-4d43-b16d-691867f26d02.png)

**Comment by Zeagl3** [comment]
Fixed in v1.1
