### ISSUE TITLE
OBody won't change bodyslide Preset

### ISSUE THREAD

**Issue by Hansamuna** [Zeagl3/Skybax#3]
The body does not change when selecting a new one in the OBody menu.

Here is what I tried to fix the issue in order: 

- rebuild morphs in BodySlide with Zeroed Sliders
- turn off bEnableBodyGen=0 ; Default[1] in racemenu skee64.ini
- add new bodyslide presets
- reinstall CBBE 3BA

Im out of time right now but I will continue testing in my freetime.

Also the racemenu morph tab in game do not work for me.

**Comment by Zeagl3** [comment]
Fixed in version 1.1
