### ISSUE TITLE
Flickering in Solitude

### ISSUE THREAD

**Issue by FiraNGit** [Zeagl3/Skybax#9]
In modified part of city
![image](https://user-images.githubusercontent.com/98646215/151701305-6ac7234c-ae6d-4d24-b561-d45352c15bf5.png)
disappearing
![image](https://user-images.githubusercontent.com/98646215/151701329-d8917584-4319-486a-bebc-28a3a8c618ad.png)
disappearing more
![image](https://user-images.githubusercontent.com/98646215/151701352-1ef48a63-7b4c-47f8-b0c2-521a255b3056.png)
reappearing
![image](https://user-images.githubusercontent.com/98646215/151701380-a7f53296-ecbe-440a-a867-08436eab29ba.png)

**Comment by Zeagl3** [comment]
Removed Enhanced Solitude untill I can fix this.
